print "<!DOCTYPE html>\n";
print "\n";
print "<!--  \n";
print "This is just a start page to access the various WebPhone skins and samples.\n";
print "There is nothing to be seen here; this index.html was created only for your convenience to easily open the various webphone skins/samples.\n";
print "-->\n";
print "\n";
print "<html>\n";
print "<head>\n";
print "    <meta http-equiv=\"content-type\" content=\"text/html; charset=windows-1252\"/>\n";
print "    <title>Webphone usage</title>\n";
print "    <meta name=\"author\" content=\"Mizutech\"/>\n";
print "    <style>\n";
print "                #js_not_enabled { float: left; clear: both; width: 100%; height: 100%; background: #1d1d1d; color: #f00; text-transform: none; text-align: center; padding: 10px; font-size: 1.2em; }\n";
print "        #header_container {\n";
print "        background-image:linear-gradient(top, #cde9f7 0%, #a2cfe6 51%);\n";
print "        background-image:-webkit-linear-gradient(top, #cde9f7 0%, #a2cfe6 51%);\n";
print "        background-image:-moz-linear-gradient(top, #cde9f7 0%, #a2cfe6 51%);\n";
print "        background-image:-ms-linear-gradient(top, #cde9f7 0%, #a2cfe6 51%);\n";
print "        background-image:-webkit-gradient(\n";
print "            linear,\n";
print "            left top,\n";
print "            left bottom,\n";
print "            color-stop(0, #cde9f7),\n";
print "            color-stop(0.51, #a2cfe6)\n";
print "        );\n";
print "        }\n";
print "        body { margin: auto; padding: 0; font-family: Verdana; font-size: 12px; color:#2e3d47; text-align: center; background: #ffffff; }\n";
print "        #header_container { width: 100%; margin: 0; padding-top: 1em; padding-bottom: 1em; height: 2.2em; }\n";
print "        #header_container h1 { margin: 0; padding: 0; font-size: 1.9em; }\n";
print "        #footer { display: inline-block; clear: both; width: 100%; \n";
print "            background-image:linear-gradient(top, #cde9f7 0%, #fff 100%);\n";
print "            background-image:-webkit-linear-gradient(top, #cde9f7 0%, #fff 100%);\n";
print "            background-image:-moz-linear-gradient(top, #cde9f7 0%, #fff 100%);\n";
print "            background-image:-ms-linear-gradient(top, #cde9f7 0%, #fff 100%);\n";
print "            background-image:-webkit-gradient(\n";
print "                linear,\n";
print "                left top,\n";
print "                left bottom,\n";
print "                color-stop(0, #cde9f7),\n";
print "                color-stop(0, #cde9f7),\n";
print "                color-stop(1, #fff)\n";
print "            );\n";
print "        }\n";
print "        #footer_cp { display: block; float: right; font-size: .75em; }\n";
print "        #footer_content { display: inline-block; width: 100%; margin: .5em 1.5em 1em 1.5em; text-align: left; line-height: 130%; font-size: .9em; }\n";
print "        #footer_links_container { display: block; width: 100%; float: left; text-align: center; margin-top: .5em; }\n";
print "        .footer_links { display: inline-block; margin-left: .3em; margin-right: .3em; }\n";
print "        #main_container { line-height: 155%; width: 900px; margin: auto; display: inline-block;\n";
print "                          /*background: #ecf3f8; border-right: solid 1px #a2cfe6; */\n";
print "                          background: #ffffff;\n";
print "        }\n";
print "        \n";
print "        #left { width: 150px; margin-right: 20px; float: left;  text-align: left; background: #ffffff; }\n";
print "        #content { float: left; text-align: center; width: 700px; background: #ffffff; margin-bottom: 3em; margin-top: .5em; }\n";
print "        #home_content, #api_content, #url_content { text-align: left; }\n";
print "        .clear { width: 100%; height: 1px; float: left; clear: both; }\n";
print "        #left_menu_list { float: left; width: 160px;  margin: 0; padding: 0; }\n";
print "        #left_menu_list .a_menu{\n";
print "            display: inline-block; width: 140px; padding-left: .5em; background: #ffffff; text-decoration: none; font-size: 1.15em; font-weight: bold; line-height: 1.7em;\n";
print "            color: #4ea6ed; margin-top: 2px;\n";
print "        }\n";
print "        #left_menu_list .a_menu:hover { background: #abd4ea;   }\n";
print "        .link_list { display: inline-block; float: left; margin: 0em 0em 2em 0em; padding-left: 0em; }\n";
print "        .link_list LI { display: inline-block; float: left; clear: both; margin-bottom: .7em; }\n";
print "        .jscode { color: #111; font-size: 1em; }\n";
print "        .code_html_tag { color: #0000e6; }\n";
print "        .code_html_commnet { color: #969696; }\n";
print "        .code_js_quotes { color: #ce7b00; }\n";
print "        .link { color: #2964d2; font-size: 12px; }\n";
print "        .frame_conatiner { overflow: hidden; }\n";
print "    </style>\n";
print "    <script src=\"js/techdemo_example/jquery-1.9.1.min.js\"></script>\n";
print "    <script>\n";
print "window.onload = function ()\n";
print "{\n";
print "    MeasurePage();\n";
print "    HandlePage();\n";
print "};\n";
print "\n";
print "var timerid;\n";
print "$( window ).resize(function() // window resize handling\n";
print "{\n";
print "    if ( typeof (timerid) !== 'undefined' && timerid !== null ) { clearTimeout(timerid); }\n";
print "    timerid = setTimeout(function ()\n";
print "    {\n";
print "        MeasurePage();\n";
print "    }, 100);\n";
print "});\n";
print "\n";
print "function HandlePage()\n";
print "{\n";
print "    var url = document.location.href;\n";
print "    if (typeof (url) === 'undefined' || url === null) { return; }\n";
print "    var pos = url.lastIndexOf('#');\n";
print "    if (pos < 1) { return; }\n";
print "    var pageid = url.substring(pos + 1);\n";
print "    if (typeof (pageid) === 'undefined' || pageid === null) { return; }\n";
print "    \n";
print "    switch (pageid)\n";
print "    {\n";
print "        case 'basic_example':\n";
print "            MenuHandler('basic');\n";
print "            break;\n";
print "        case 'techdemo_example':\n";
print "            MenuHandler('techdemo');\n";
print "            break;\n";
print "        case 'softphone':\n";
print "            MenuHandler('softphone');\n";
print "            break;\n";
print "        case 'mobile_example':\n";
print "            MenuHandler('mobile');\n";
print "            break;\n";
print "        case 'click2call':\n";
print "            MenuHandler('click2call');\n";
print "            break;\n";
print "        case 'linkify_example':\n";
print "            MenuHandler('linkify_example');\n";
print "            break;\n";
print "        case 'api_example':\n";
print "            MenuHandler('api');\n";
print "            break;\n";
print "        case 'htmlurl':\n";
print "            MenuHandler('htmlurl');\n";
print "            break;\n";
print "        case 'more':\n";
print "            MenuHandler('manymore');\n";
print "            break;\n";
print "    }\n";
print "}\n";
print "\n";
print "function MeasurePage()\n";
print "{\n";
print "    $(\"#content\").width( $(\"#main_container\").width() - $(\"#left\").width() - 40 );\n";
print "    $(\"#left\").height( $(\"#content\").height() );\n";
print "}\n";
print "\n";
print "function MenuHandler(id)\n";
print "{\n";
print "    if (typeof (id) === 'undefined' || id.length < 1) { return; }\n";
print "    \n";
print "    var open_in_new_tab = false;\n";
print "// skin does not work in IE8 in iframe, so open it in new page\n";
print "    if (IsIeVersion3(8) === true && (id === 'techdemo' || id === 'basic' || id === 'softphone' || id === 'mobile' || id === 'click2call' || id === 'basic_example')) { open_in_new_tab = true; }\n";
print "    \n";
print "    if (open_in_new_tab !== true)\n";
print "    {\n";
print "        $(\"#home_content\").hide();\n";
print "        $(\"#alternate_content\").html('');\n";
print "        $(\"#alternate_content\").hide();\n";
print "        $(\"#api_content\").hide();\n";
print "        $(\"#url_content\").hide();\n";
print "        $(\"#manymore\").hide();\n";
print "    }\n";
print "    \n";
print "    \n";
print "    var ifrm_template = '<iframe allow=\"microphone; camera\" allowfullscreen=\"true\" frameborder=\"0\" width=\"[WIDTH]\" height=\"[HEIGHT]\" src=\"[SOURCE]\" name=\"[NAME]\" id=\"[ID]\" class=\"frame_conatiner\" scrolling=\"no\"></iframe>';\n";
print "    \n";
print "    if (id === 'home')\n";
print "    {\n";
print "        $(\"#home_content\").show();\n";
print "    }\n";
print "    else if (id === 'techdemo')\n";
print "    {\n";
print "        var urltmp = 'samples/techdemo_example.html?isdemopage=true';\n";
print "        if (open_in_new_tab === true)\n";
print "        {\n";
print "            window.open(urltmp);\n";
print "            return;\n";
print "        }\n";
print "\n";
print "        var ifrm = ifrm_template.replace('[SOURCE]', urltmp);\n";
print "        ifrm = ifrm.replace('[NAME]', 'techdemo');\n";
print "        ifrm = ifrm.replace('[ID]', 'techdemo');\n";
print "        ifrm = ifrm.replace('[WIDTH]', '100%');\n";
print "        ifrm = ifrm.replace('[HEIGHT]', '620');\n";
print "        \n";
print "        $(\"#alternate_content\").html(ifrm);\n";
print "        $(\"#alternate_content\").show();\n";
print "    }\n";
print "    else if (id === 'basic')\n";
print "    {\n";
print "        var urltmp = 'samples/basic_example.html?isdemopage=true';\n";
print "        if (open_in_new_tab === true)\n";
print "        {\n";
print "            window.open(urltmp);\n";
print "            return;\n";
print "        }\n";
print "\n";
print "        var ifrm = ifrm_template.replace('[SOURCE]', urltmp);\n";
print "        ifrm = ifrm.replace('[NAME]', 'basic');\n";
print "        ifrm = ifrm.replace('[ID]', 'basic');\n";
print "        ifrm = ifrm.replace('[WIDTH]', '100%');\n";
print "        ifrm = ifrm.replace('[HEIGHT]', '350');\n";
print "        \n";
print "        $(\"#alternate_content\").html(ifrm);\n";
print "        $(\"#alternate_content\").show();\n";
print "    }\n";
print "    else if (id === 'softphone')\n";
print "    {\n";
print "        var urltmp = 'softphone.html?isdemopage=true';\n";
print "        if (open_in_new_tab === true)\n";
print "        {\n";
print "            window.open(urltmp);\n";
print "            return;\n";
print "        }\n";
print "        \n";
print "        var ifrm = ifrm_template.replace('[SOURCE]', urltmp);\n";
print "        ifrm = ifrm.replace('[NAME]', 'softphone');\n";
print "        ifrm = ifrm.replace('[ID]', 'softphone');\n";
print "        ifrm = ifrm.replace('[WIDTH]', '350');\n";
print "        ifrm = ifrm.replace('[HEIGHT]', '540');\n";
print "        \n";
print "        var txt = '<span style=\"font-family: Tahoma, Arial ; font-size: 16px; color:#4eaaec; text-alignalign:left\">Softphone</span><br><br><div>A customizable turn-key browser softphone implementation. <br />You can use it as-is or customize via the various webphone parameters <br />(or change its html/css/js after your needs if you are a JavaScript developer).</div><br />';\n";
print "        $(\"#alternate_content\").html(txt + ifrm);\n";
print "        $(\"#alternate_content\").show();\n";
print "    }\n";
print "    else if (id === 'mobile')\n";
print "    {\n";
print "        var urltmp = 'samples/mobile_example.html?isdemopage=true';\n";
print "        if (open_in_new_tab === true)\n";
print "        {\n";
print "            window.open(urltmp);\n";
print "            return;\n";
print "        }\n";
print "\n";
print "        var ifrm = ifrm_template.replace('[SOURCE]', urltmp);\n";
print "        ifrm = ifrm.replace('[NAME]', 'mobile');\n";
print "        ifrm = ifrm.replace('[ID]', 'mobile');\n";
print "        ifrm = ifrm.replace('[WIDTH]', '350');\n";
print "        ifrm = ifrm.replace('[HEIGHT]', '780');\n";
print "        \n";
print "        $(\"#alternate_content\").html(ifrm);\n";
print "        $(\"#alternate_content\").show();\n";
print "    }\n";
print "    else if (id === 'click2call')\n";
print "    {\n";
print "        var urltmp = 'click2call.html?isdemopage=true';\n";
print "        if (open_in_new_tab === true)\n";
print "        {\n";
print "            window.open(urltmp);\n";
print "            return;\n";
print "        }\n";
print "\n";
print "        var ifrm = ifrm_template.replace('[SOURCE]', urltmp);\n";
print "        ifrm = ifrm.replace('[NAME]', 'click2call');\n";
print "        ifrm = ifrm.replace('[ID]', 'click2call');\n";
print "        ifrm = ifrm.replace('[WIDTH]', '100%');\n";
print "        ifrm = ifrm.replace('[HEIGHT]', '630');\n";
print "        \n";
print "        var extrahtml = '';\n";
print "       /*\n";
print "        var extrahtml = 'These configurations can be set in the .html source, but just for this online demo, you can enter the configuration below:<br /><br />' +\n";
print "                        '<input type=\"text\" placeholder=\"VoIP Server address\" id=\"c2c_serveraddress\"><br />' +\n";
print "                        '<input type=\"text\" placeholder=\"Username\" id=\"c2c_username\"><br />' +\n";
print "                        '<input type=\"text\" placeholder=\"Password\" id=\"c2c_password\"><br />' +\n";
print "                        '<input type=\"text\" placeholder=\"Callto\" id=\"c2c_callto\"><br />';\n";
print "       */\n";
print "        $(\"#alternate_content\").html(ifrm + extrahtml);\n";
print "        $(\"#alternate_content\").show();\n";
print "        /*\n";
print "        setTimeout(function ()\n";
print "        {\n";
print "            var ifrm = document.getElementById('click2call');\n";
print "            var iwindow = ifrm.contentWindow || ifrm;\n";
print "            \n";
print "            if (typeof (iwindow) === 'undefined' || iwindow === null) { return; }\n";
print "            \n";
print "            var c2c_serveraddress_input = document.getElementById('c2c_serveraddress');\n";
print "            var c2c_username_input = document.getElementById('c2c_username');\n";
print "            var c2c_password_input = document.getElementById('c2c_password');\n";
print "            var c2c_destination_input = document.getElementById('c2c_callto');\n";
print "            \n";
print "            var serveraddress = iwindow.webphone_api.getparameter('serveraddress');\n";
print "            var username = iwindow.webphone_api.getparameter('username');\n";
print "            var password = iwindow.webphone_api.getparameter('password');\n";
print "            var destination = iwindow.webphone_api.getparameter('destination');\n";
print "            \n";
print "            if (serveraddress.length > 0) { c2c_serveraddress_input.value = serveraddress; }\n";
print "            if (username.length > 0) { c2c_username_input.value = username; }\n";
print "            if (password.length > 0) { c2c_password_input.value = password; }\n";
print "            if (destination.length > 0) { c2c_destination_input.value = destination; }\n";
print "        }, 5000);*/\n";
print "    }\n";
print "    else if (id === 'linkify_example')\n";
print "    {\n";
print "        var ifrm = ifrm_template.replace('[SOURCE]', 'samples/linkify_example.html');\n";
print "        ifrm = ifrm.replace('[NAME]', 'linkify_example');\n";
print "        ifrm = ifrm.replace('[ID]', 'linkify_example');\n";
print "        ifrm = ifrm.replace('[WIDTH]', '100%');\n";
print "        ifrm = ifrm.replace('[HEIGHT]', '300');\n";
print "        \n";
print "        $(\"#alternate_content\").html(ifrm);\n";
print "        $(\"#alternate_content\").show();\n";
print "    }\n";
print "    else if (id === 'basic_example')\n";
print "    {\n";
print "        var urltmp = 'samples/basic_example.html';\n";
print "        if (open_in_new_tab === true)\n";
print "        {\n";
print "            window.open(urltmp);\n";
print "            return;\n";
print "        }\n";
print "\n";
print "        var ifrm = ifrm_template.replace('[SOURCE]', urltmp);\n";
print "        ifrm = ifrm.replace('[NAME]', 'basic_example');\n";
print "        ifrm = ifrm.replace('[ID]', 'basic_example');\n";
print "        ifrm = ifrm.replace('[WIDTH]', '100%');\n";
print "        ifrm = ifrm.replace('[HEIGHT]', '350');\n";
print "        \n";
print "        $(\"#alternate_content\").html(ifrm);\n";
print "        $(\"#alternate_content\").show();\n";
print "    }\n";
print "    else if (id === 'api')\n";
print "    {\n";
print "        $(\"#api_content\").show();\n";
print "    }\n";
print "    else if (id === 'htmlurl')\n";
print "    {\n";
print "        $(\"#url_content\").show();\n";
print "    }\n";
print "    else if (id === 'manymore')\n";
print "    {\n";
print "        $(\"#manymore\").show();\n";
print "    }\n";
print "	\n";
print "    else if (id === 'php_example')\n";
print "    {\n";
print "        var ifrm = ifrm_template.replace('[SOURCE]', 'samples/php_example.html');\n";
print "        ifrm = ifrm.replace('[NAME]', 'php_example');\n";
print "        ifrm = ifrm.replace('[ID]', 'php_example');\n";
print "        ifrm = ifrm.replace('[WIDTH]', '100%');\n";
print "        ifrm = ifrm.replace('[HEIGHT]', '700');\n";
print "		\n";
print "		ifrm = ifrm.replace('class=\"frame_conatiner\"', '');\n";
print "        ifrm = ifrm.replace('scrolling=\"no\"', '');\n";
print "        \n";
print "        $(\"#alternate_content\").html(ifrm);\n";
print "        $(\"#alternate_content\").show();\n";
print "    }\n";
print "    else if (id === 'callcenter')\n";
print "    {\n";
print "        var ifrm = ifrm_template.replace('[SOURCE]', 'samples/callcenter.html');\n";
print "        ifrm = ifrm.replace('[NAME]', 'callcenter');\n";
print "        ifrm = ifrm.replace('[ID]', 'callcenter');\n";
print "        ifrm = ifrm.replace('[WIDTH]', '120%');\n";
print "        ifrm = ifrm.replace('[HEIGHT]', '700');\n";
print "		\n";
print "		ifrm = ifrm.replace('class=\"frame_conatiner\"', '');\n";
print "        ifrm = ifrm.replace('scrolling=\"no\"', '');\n";
print "        \n";
print "        $(\"#alternate_content\").html(ifrm);\n";
print "        $(\"#alternate_content\").show();\n";
print "    }\n";
print "	else if (id === 'many')\n";
print "    {\n";
print "        var ifrm = ifrm_template.replace('[SOURCE]', 'samples/more_example.html');\n";
print "        ifrm = ifrm.replace('[NAME]', 'many');\n";
print "        ifrm = ifrm.replace('[ID]', 'many');\n";
print "        ifrm = ifrm.replace('[WIDTH]', '100%'); \n";
print "        ifrm = ifrm.replace('[HEIGHT]', '700');\n";
print "		\n";
print "		ifrm = ifrm.replace('class=\"frame_conatiner\"', '');\n";
print "        ifrm = ifrm.replace('scrolling=\"no\"', '');\n";
print "        \n";
print "        $(\"#alternate_content\").html(ifrm);\n";
print "        $(\"#alternate_content\").show();\n";
print "    }\n";
print "    /*\n";
print "    setTimeout(function ()\n";
print "    {\n";
print "        MeasurePage();\n";
print "    }, 100);*/\n";
print "}\n";
print "function IsIeVersion3 (version) // :boolean  check if it is IE browser version xxx\n";
print "{\n";
print "    try{\n";
print "    if (typeof(version) === 'undefined' || version === null) { return false; }\n";
print "\n";
print "    var agent = navigator.userAgent;\n";
print "    var msie = agent.indexOf('MSIE ');\n";
print "    var currver = 0;\n";
print "    if (msie > 0)\n";
print "    {\n";
print "        // IE 10 or older => return version number\n";
print "        currver = parseInt(agent.substring(msie + 5, agent.indexOf('.', msie)), 10);\n";
print "        if (version === currver) { return  true; }\n";
print "    }\n";
print "    } catch(err) { ; }\n";
print "    return false;\n";
print "}\n";
print "</script>\n";
print "</head>\n";
print "<body lang=\"en-US\" link=\"#0000ff\" dir=\"ltr\" spellcheck=\"false\">\n";
print "\n";
print "<div id=\"js_not_enabled\">Enable JavaScript or click the "Allow" button in your browser!!!</div>\n";
print "<script type=\"text/javascript\">document.getElementById('js_not_enabled').style.display = 'none'; try{ document.getElementById('phone_app_main_container').style.display = 'none'; } catch(err) {  }</script>\n";
print "<!-- <div id=\"header_container\">\n";
print "    <h1 class=\"western\" align=\"center\">Mizutech Webphone</h1>\n";
print "</div> -->\n";
print "<div id=\"main_container\">\n";
print "    <div id=\"left\">\n";
print "        <div id=\"left_menu_list\">\n";
print "            <a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('home')\">Home</a><br /><br />\n";
print "            <a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('basic')\">Basic</a>\n";
print "            <a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('techdemo')\" style=\"padding-left: .4em;\">Tech demo</a>\n";
print "            <a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('softphone')\" style=\"padding-left: .4em;\">Softphone</a>\n";
print "            <a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('mobile')\" style=\"padding-left: .4em;\">Mobile</a>\n";
print "            <a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('click2call')\">Click to call</a>\n";
print "            <a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('linkify_example')\">Linkify</a>\n";
print "            <a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('api')\">API</a>\n";
print "            <a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('htmlurl')\">HTML URL</a>\n";
print "			<!-- <a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('php_example')\">PHP</a>\n";
print "			<a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('callcenter')\">Call center</a> -->\n";
print "			<a href=\"javascript:;\" class=\"a_menu\" onclick=\"MenuHandler('manymore')\">More</a>\n";
print "			<!--\n";
print "            <br /><br /><br />\n";
print "            <a href=\"https://www.mizu-voip.com/Software/WebPhone.aspx\" class=\"a_menu\" target=\"_blank\">Homepage</a>\n";
print "            <a href=\"https://www.mizu-voip.com/Portals/0/Files/Webphone_Documentation.pdf\" class=\"a_menu\" target=\"_blank\">Documentation</a>\n";
print "            <a href=\"https://www.mizu-voip.com/Portals/0/Files/webphone.zip\" class=\"a_menu\" target=\"_blank\">Download</a>\n";
print "			-->\n";
print "        </div>\n";
print "    </div>\n";
print "    <div id=\"content\" align=\"left\">\n";
print "        \n";
print "        <!--<h3 class=\"western\" align=\"center\"><font size=\"3\" style=\"font-size: 16pt\">Usage examples</font></h3><br />-->\n";
print "        <div id=\"home_content\">\n";
print "		<div style=\"font-family: Tahoma, Arial ; font-size: 16px; color:#4eaaec; text-align:center\">Home</div><br>\n";
print "		\n";
print "            The Mizutech <a href=\"https://www.mizu-voip.com/Software/WebPhone.aspx\" target=\"_blank\">webphone</a>  is a SIP client for browsers, implementing multiple engines\n";
print "to take advantage of the best available client-side VoIP\n";
print "technology across the majority of OS and browsers, including Java\n";
print "Applet, HTML5/WebRTC, Native Plugin service, Flash and others covered\n";
print "by a simple to use universal API and customizable user interface templates.\n";
print "<br /><br />\n";
print "This is a simple index page with direct links to the examples shipped with the webphone package. You are free to use any of the included solutions, modify/customize each of the supplied HTML/CSS code or implement your VoIP client from scratch by providing your own user interface (or no user interface at all) using the webphone's Java Script API.\n";
print "<br />\n";
print "Try out the solutions/examples from the left side to quickly check the webphone functionalities. This page is part of the <a href=\"https://www.mizu-voip.com/Portals/0/Files/webphone.zip\">downloadable webphone package</a>. Check the source codes for more details (softphone.html and the html files in the samples folder).\n";
print "<br /><br /> \n";
print "If you don't have a SIP server or VoIP account yet, you can use our <a href=\"https://www.mizu-voip.com/Services/VoIPServices.aspx\" target=\"_blank\">VoIP service</a>:\n";
print "<ul class=\"link_list3\" style=\"list-style:none\">\n";
print "<li>- Server address: voip.mizu-voip.com</li>\n";
print "<li>- Account: create <a href=\"https://voip.mizu-voip.com/?function=newuser\" target=\"_blank\">free VoIP account from here</a> or use the following username/passwords: webphonetest1/webphonetest1, webphonetest2/webphonetest2 (others might also use these public accounts so calls might be misrouted)</li>\n";
print "<li>- Call: You can call the \"testivr3\" access number to hear a music or register with both accounts and call each others (you can also use one account for webphone and the other one for a regular SIP client)</li>\n";
print "</ul>\n";
print "\n";
print "\n";
print "            <div class=\"clear\"><!--//--></div>\n";
print "            \n";
print "            <div class=\"clear\"><!--//--></div>\n";
print "            <ul class=\"link_list\">\n";
print "				<li><a href=\"javascript:;\" onclick=\"MenuHandler('basic')\">Basic</a>: simplest usage example (not for production) [basic_example.html]</li>\n";
print "				<li><a href=\"javascript:;\" onclick=\"MenuHandler('techdemo')\">Tech Demo</a>: try out the webphone by using this simple demo. You can also use this as a starting template for your custom development [techdemo_example.html / techdemo_example.js]</li>\n";
print "				<li><a href=\"javascript:;\" onclick=\"MenuHandler('softphone')\">Softphone</a>: implements a full featured VoIP softphone in browser which can be used as is [softphone_launch.html/softphone.html/softphone folder]</li>	\n";
print "				<li><a href=\"javascript:;\" onclick=\"MenuHandler('mobile')\">Mobile</a>: the webphone works also on mobile. This is just a show-case [mobile_example.html]</li>\n";
print "                <li><a href=\"javascript:;\" onclick=\"MenuHandler('click2call')\">Click to call</a>: click to call button [click2call.html / click2call.js]</li>\n";
print "                <li><a href=\"javascript:;\" onclick=\"MenuHandler('linkify_example')\">Linkify</a>: convert all phone number like strings on your website to click to call links [linkify_example.html / linkify.js]</li>\n";
print "				<li><a href=\"javascript:;\" onclick=\"MenuHandler('api')\">API</a>: use the \"webphone_api.js\" file. Check the examples and the documentation for the usage.</li>\n";
print "				<li><a href=\"javascript:;\" onclick=\"MenuHandler('htmlurl')\">HTML URL</a>: the webphone can load its settings also from the webpage URL and perform various actions such as initiate a call.</li>\n";
print "				<!-- <li><a href=\"javascript:;\" onclick=\"MenuHandler('php_example')\">PHP</a>: the webphone can be integrated easily into a PHP based website</li>\n";
print "				<li><a href=\"javascript:;\" onclick=\"MenuHandler('callcenter')\">Call center</a>: webphone usage for callcenters</li> -->\n";
print "				<li>There are <a href=\"javascript:;\" onclick=\"MenuHandler('manymore')\">many other</a> ways to use the webphone.</li>\n";
print "            </ul>\n";
print "            <br><br>\n";
print "            <div class=\"clear\"><!--//--></div>			\n";
print "			<br /><br />\n";
print "			For more details <a href=\"https://www.mizu-voip.com/Portals/0/Files/webphone.zip\" target=\"_blank\">download</a> or check the <a href=\"https://www.mizu-voip.com/Portals/0/Files/Webphone_Documentation.pdf\" target=\"_blank\">documentation</a>.\n";
print "			<br /><br />\n";
print "            <div class=\"clear\"><!--//--></div>\n";
print "        </div>\n";
print "        <div id=\"alternate_content\" style=\"display: none;\"></div>\n";
print "        <div id=\"api_content\" style=\"display: none;\">\n";
print "<div style=\"font-family: Verdana ; font-size: 16px; color:#4eaaec; text-align:center\">JavaScript API</div><br><br>            \n";
print "The public JavaScript API can be found in \"webphone_api.js\" file, under global javascript namespace \"webphone_api\".\n";
print "To be able to use the webphone as a javascript VoIP library, just copy the webphone folder to your web project and add the webphone_api.js to your page.\n";
print "Simple example:<br /><br /><br />\n";
print "            <div class=\"jscode\">\n";
print "                <span class=\"code_html_tag\"><head></span><br />\n";
print "      <span class=\"code_html_commnet\"><!--include the webphone_api.js to your webpage--></span><br />\n";
print "      <span class=\"code_html_tag\"><script src=</span><span class=\"code_js_quotes\">\"webphone_api.js\"</span><span class=\"code_html_tag\">></script></span><br />\n";
print "<span class=\"code_html_tag\"></head></span><br />\n";
print "<span class=\"code_html_tag\"><body></span><br />\n";
print "      <span class=\"code_html_tag\"><script></span><br />\n";
print "\n";
print "      <span class=\"code_html_commnet\">// IMPORTANT: Wait until the webphone is loaded, before calling any API functions</span><br />\n";
print "      webphone_api.onAppStateChange(function (state) {<br />\n";
print "      if (state === <span class=\"code_js_quotes\">'loaded'</span>) {<br /><br />\n";
print "\n";
print "            <span class=\"code_html_commnet\">//set parameters (alternatively these can be also preset in your html)</span><br />\n";
print "            webphone_api.setparameter(<span class=\"code_js_quotes\">'serveraddress'</span>, SERVERADDRESS); <span class=\"code_html_commnet\">// Replace the word in uppercase with your SIP server IP or domain name (add also the :port number if not using the standard UDP 5060)</span><br />\n";
print "            webphone_api.setparameter(<span class=\"code_js_quotes\">'username'</span>, USERNAME); <span class=\"code_html_commnet\">// Replace the word in uppercase with a valid SIP extension username</span><br />\n";
print "            webphone_api.setparameter(<span class=\"code_js_quotes\">'password'</span>, PASSWORD); <span class=\"code_html_commnet\">// Replace the word in uppercase with the password for the above user</span><br />\n";
print "            <span class=\"code_html_commnet\">//see the ï¿½Parametersï¿½ section in the documentation for more options</span><br /><br />\n";
print "            <span class=\"code_html_commnet\">//start the webphone (optional but recommended)</span><br />\n";
print "            webphone_api.start();<br />\n";
print "            <span class=\"code_html_commnet\">//make a call (usually initiated by user action, such as click on a click to call button)</span><br />\n";
print "            webphone_api.call(number);<br />\n";
print "            <span class=\"code_html_commnet\">//hangup</span><br />\n";
print "            webphone_api.hangup();<br />\n";
print "            <span class=\"code_html_commnet\">//send instant message</span><br />\n";
print "            webphone_api.sendchat(number, message);<br />\n";
print "      }<br />\n";
print "      });<br />\n";
print "      <span class=\"code_html_tag\"></script></span><br />\n";
print "<span class=\"code_html_tag\"></body></span>\n";
print "<br /><br /><br />\n";
print "For more details consult the Javascript API section in the <a href=\"https://www.mizu-voip.com/Portals/0/Files/Webphone_Documentation.pdf\" target=\"_blank\">documentation</a>.\n";
print "<br />\n";
print "            </div>\n";
print "        </div>\n";
print "        <div id=\"url_content\" style=\"display: none;\">\n";
print "		<div style=\"font-family: Verdana; font-size: 16px; color:#4eaaec; text-align:center\">HTML URL</div><br><br>\n";
print "The webphone can load its settings also from the webpage URL and perform various actions such as initiate a call. All the documented parameters can be used, prefixed\n";
print "with ï¿½wp_ï¿½.<br /><br />\n";
print "Example to trigger a call with the softphone by html url parameters:<br />\n";
print "<span class=\"link\">http://www.yourwebsite.com/webphonedir/softphone.html?wp_serveraddress=YOURSIPDOMAIN&wp_username=USERNAME&wp_password=PASSWORD&wp_callto=CALLEDNUMBER</span><br /><br />\n";
print "Example to trigger a call with the clicktocall by html url parameters:<br />\n";
print "<span class=\"link\">http://www.yourwebsite.com/webphonedir/click2call.html?wp_serveraddress=YOURSIPDOMAIN&wp_username=USERNAME&wp_password=PASSWORD&wp_callto=CALLEDNUMBER</span><br /><br />\n";
print "A working example using the click to call button:<br />\n";
print "<a href=\"https://www.webvoipphone.com/webphone_online_demo/click2call.html?wp_serveraddress=voip.mizu-voip.com&wp_username=webphonetest1&wp_password=webphonetest1&wp_callto=testivr3&wp_autoaction=1\" target=\"_blank\">https://www.webvoipphone.com/webphone_online_demo/click2call.html?wp_serveraddress=voip.mizu-voip.com&wp_username=webphonetest1&wp_password=webphonetest1&wp_callto=testivr3&wp_autoaction=1</a>\n";
print "<br /><br />\n";
print "A working example using the softhone skin:<br />\n";
print "<a href=\"https://www.webvoipphone.com/webphone_online_demo/softphone.html?wp_serveraddress=voip.mizu-voip.com&wp_username=webphonetest1&wp_password=webphonetest1&wp_callto=testivr3&wp_autoaction=1\" target=\"_blank\">https://www.webvoipphone.com/webphone_online_demo/samples/click2call.html?wp_serveraddress=voip.mizu-voip.com&wp_username=webphonetest1&wp_password=webphonetest1&wp_callto=testivr3&wp_autoaction=1</a>\n";
print "<br /><br />\n";
print "Example trigger chat by html parameters<br />\n";
print "<span class=\"link\">http://www.yourwebsite.com/webphonedir/softphone.html?wp_serveraddress=YOURSIPDOMAIN&wp_username=USERNAME&wp_password=PASSWORD&wp_sendchat=TEXT&wp_to=DESTINATION</span><br /><br />\n";
print "Note: you should use clear text password only if the account is locked on your server (canï¿½t call costly outside numbers). Otherwise you should pass it encrypted or\n";
print "use MD5 instead.<br /><br />\n";
print "        </div>\n";
print "    \n";
print "	\n";
print "	<div id=\"manymore\" style=\"display: none;\">\n";
print "		<div style=\"font-family: Verdana; font-size: 16px; color:#4eaaec; text-align:center\">Many more</div><br><br>\n";
print "<div style=\"text-align:left\">There are many other ways to use the webphone. See the \"Usage examples\" on the <a href=\"https://www.mizu-voip.com/Software/WebPhone.aspx\" target=\"_blank\">home page</a> for some suggestions. \n";
print "	You can create your own solutions for scratch using the WebPhone API or modify the existing examples after your needs. \n";
print "	There is no need for any JavaScipt or other development knowledge if you just need a web softphone or click to call solution for your website. (Use the \"softphone.html\" or the \"click2call.html\" as-is or customize them after your needs viat the webphone parameters which you can set in the \"webphone_config.js\" file).\n";
print "	<br />\n";
print "	You can also find various other examples from the webphone documentation. For example <a href=\"https://www.mizu-voip.com/Portals/0/Files/voicerechandler.txt\" target=\"_blank\">php voice recording upload</a>,  <a href=\"https://www.mizu-voip.com/Portals/0/Files/SalesforceWebPhone.pdf\" target=\"_blank\">salesforce web sip client integration</a> or see the \"multipage_example.html\" about using a single webphone instances across all web pages.\n";
print "	<br />\n";
print "	For a quick tutorial, check <a href=\"https://www.mizu-voip.com/Support/Wiki/tabid/99/Default.aspx?topic=WebPhone+Quick+Start\" target=\"_blank\">here</a>.\n";
print "	\n";
print "	<br />\n";
print "	<br />\n";
print "	The rest is your imagination.\n";
print "<br>\n";
print "\n";
print "</div>\n";
print "</div>\n";
print "    </div>\n";
print "<!-- <div id=\"footer\">\n";
print "    <div id=\"footer_content\">\n";
print "        Problems running the demo? Send an email to <a href=\"mailto:webphone@mizu-voip.com?subject=Webphone\">webphone@mizu-voip.com</a> with a \n";
print "        short description about the problem/question with the <br /> <a href=\"https://www.mizu-voip.com/Support/Wiki/tabid/99/Default.aspx?topic=Webphone+logs\" target=\"_blank\">browser console logs</a> about your attempt and we will check it asap. If possible please send us also a test account valid on your SIP server.\n";
print "        <br /><br />\n";
print "        <div id=\"footer_links_container\">\n";
print "            <span class=\"footer_links\"><a href=\"https://www.mizu-voip.com/\" target=\"_blank\">Mizutech</a></span>|\n";
print "            <span class=\"footer_links\"><a href=\"https://www.mizu-voip.com/Software/WebPhone.aspx\" target=\"_blank\">Webphone</a></span>|\n";
print "            <span class=\"footer_links\"><a href=\"https://www.mizu-voip.com/Portals/0/Files/Webphone_Documentation.pdf\" target=\"_blank\">Documentation</a></span>|\n";
print "            <span class=\"footer_links\"><a href=\"https://www.mizu-voip.com/Portals/0/Files/webphone.zip\" target=\"_blank\">Download</a></span>|\n";
print "            <span class=\"footer_links\"><a href=\"https://www.mizu-voip.com/Support.aspx\" target=\"_blank\">Support</a></span>|\n";
print "            <span class=\"footer_links\"><a href=\"https://www.mizu-voip.com/Company/Contact.aspx\" target=\"_blank\">Contact</a></span>\n";
print "        </div>\n";
print "    </div>\n";
print "    <div id=\"footer_cp\">Copyright (c) 2017 Mizutech S.R.L.</div>\n";
print "</div>\n";
print "</div> -->\n";
print "</body>\n";
print "</html>";
